-- ============================================================================
-- SIGNula Database Migration 042
--
-- Copyright (c) 2025-2026 MWBM Partners Ltd (t/a MWservices). All rights reserved.
--
-- 📋 Migration: Data-Driven Regime Configuration Model (G-004 Layer 3 §4)
-- 📅 Date:      2026-07-10
-- 🔖 Version:   2.7.0-beta
-- 📝 Description:
--   The core that makes "18+ data-protection regimes without code sprawl"
--   true: every jurisdiction-specific number/right/threshold/window/
--   disclosure lives in these tables, never hardcoded in PHP. Creates:
--     - tblComplianceRegimes   : one row per regime (GDPR, CCPA, LGPD, ...).
--                                ALL legal VALUES (SLA days, min age, breach
--                                window, authority contact) are user/legal
--                                supplied — seeded here as NULL placeholders.
--     - tblRegimeRights        : which DSAR rights (tblDataSubjectRequests.
--                                requestType union) a regime grants.
--     - tblRegimeDisclosures   : required disclosure sections per regime —
--                                title/body ship EMPTY; body is USER/LEGAL
--                                content, never generated by this migration.
--     - tblRegimeResolution    : the rule table RegimeResolver walks
--                                (country/region/partner/default → regimeID)
--                                to decide which regime governs a request.
--   Plus ONE tblSettings row (privacy category) for the generic,
--   country-agnostic most-protective-default minimum age fallback that
--   RegimeResolver::minAgeFor() uses when no active regime resolves.
--
--   ⚠️ NO REGIME IS EVER AUTO-ACTIVATED BY THIS MIGRATION. Every one of the
--   19 seeded regimes ships `isActive = 0, isDraft = 1` with its
--   dsarSlaDays / dsarExtensionDays / breachNotifyHours /
--   breachNotifyAuthority / minAge value columns left NULL — these are
--   legal-judgement values that only an operator + counsel may confirm and
--   activate (a later admin-CRUD cycle, G-004 spec §4.3, is NOT built by
--   this migration). Well-known PUBLIC anchor numbers (e.g. "GDPR is
--   commonly cited as 30 days / 72 hours") are offered ONLY as free-text
--   *suggestions* inside the `notes` column, clearly labelled "confirm with
--   legal" — they are NEVER written into the actual value columns, and
--   nothing here treats them as authoritative. RegimeResolver (the PHP
--   class this migration exists to support) reads ROWS, never regime code
--   literals — adding a 19th/20th regime is a row insert, zero PHP edits.
--
--   The 4 boolean CHARACTERISTIC flags (`honorsGPC`, `requiresDoNotSell`,
--   `lawfulBasisRequired`, and by extension `isActive`) are ALSO left at
--   their safe table DEFAULT (0) for every seeded regime, for the identical
--   reason the numeric columns stay NULL: whether e.g. CCPA "requires"
--   Do-Not-Sell is itself a configuration decision this migration declines
--   to make on the operator's behalf while the row is still `isDraft = 1` —
--   the future admin-CRUD activation workflow is where an owner deliberately
--   sets these, informed by the `notes` suggestions below.
--
--   tblRegimeResolution.regimeID is declared NULLABLE, WITHOUT a foreign key
--   (deviates from the earlier spec draft's `NOT NULL` + FK sketch — see the
--   table's own comment block below for the justification: the seeded
--   'default' rule intentionally carries regimeID = NULL, since — with every
--   regime inactive — resolution is expected to fall through to
--   RegimeResolver's synthetic most-protective PHP default regardless of
--   this table's contents).
--
-- 🔗 Related: .dev-team/specs/G-004.md §4 (4.1-4.4 — Layer 3, the
--    data-driven regime configuration model), web/private_html/compliance/
--    RegimeResolver.php (the ONLY PHP that reads these tables),
--    _database/migrations/040_consent_and_dsar.sql (tblDataSubjectRequests.
--    regimeCode / dueDate — the retro-wired consumer of this resolver),
--    _database/migrations/041_consent_categories_and_policy_versions.sql
--    (tblConsentRecords.regimeCode — the other retro-wired consumer).
-- ============================================================================

-- ============================================================================
-- 🏗️ CREATE COMPLIANCE REGIMES TABLE
-- ============================================================================
-- 🌍 One row per regime. ALL jurisdiction VALUES live here, never in PHP.
-- See the migration header for why every seeded row below ships with its
-- value columns NULL and isActive = 0 / isDraft = 1.
-- ============================================================================

CREATE TABLE IF NOT EXISTS `tblComplianceRegimes` (
    `regimeID`              SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `regimeCode`            VARCHAR(16) NOT NULL
        COMMENT 'Stable short code, e.g. GDPR, UK_GDPR, CCPA, CPRA, LGPD — the ONLY place a regime name may appear as literal DATA (never in PHP logic)',
    `displayName`           VARCHAR(128) NOT NULL
        COMMENT 'Human-readable regime name, e.g. "General Data Protection Regulation"',
    `jurisdiction`          VARCHAR(64) NULL DEFAULT NULL
        COMMENT 'Country/region label — descriptive, user-editable',
    `dsarSlaDays`           SMALLINT UNSIGNED NULL DEFAULT NULL
        COMMENT 'DSAR fulfilment SLA in days — USER/LEGAL-SUPPLIED, ships NULL',
    `dsarExtensionDays`     SMALLINT UNSIGNED NULL DEFAULT NULL
        COMMENT 'Permitted SLA extension where the regime allows one — USER/LEGAL-SUPPLIED, ships NULL',
    `breachNotifyHours`     SMALLINT UNSIGNED NULL DEFAULT NULL
        COMMENT 'Breach notification window to the supervisory authority, in hours — USER/LEGAL-SUPPLIED, ships NULL',
    `breachNotifyAuthority` VARCHAR(255) NULL DEFAULT NULL
        COMMENT 'Supervisory authority name/contact for breach notification — USER/LEGAL-SUPPLIED, ships NULL',
    `minAge`                TINYINT UNSIGNED NULL DEFAULT NULL
        COMMENT 'Digital-consent minimum age threshold — USER/LEGAL-SUPPLIED, ships NULL',
    `honorsGPC`             TINYINT(1) NOT NULL DEFAULT 0
        COMMENT 'Does this regime treat Global Privacy Control as a valid opt-out signal — ships 0 (unconfirmed) for every seed row',
    `requiresDoNotSell`     TINYINT(1) NOT NULL DEFAULT 0
        COMMENT 'Does this regime require a "Do Not Sell/Share" mechanism — ships 0 (unconfirmed) for every seed row',
    `lawfulBasisRequired`   TINYINT(1) NOT NULL DEFAULT 0
        COMMENT 'Does this regime require a recorded lawful basis per processing activity (GDPR-style) — ships 0 (unconfirmed) for every seed row',
    `isActive`              TINYINT(1) NOT NULL DEFAULT 0
        COMMENT 'OFF by default for every regime — an operator activates only after legal review; RegimeResolver NEVER returns an inactive regime',
    `isDraft`               TINYINT(1) NOT NULL DEFAULT 1
        COMMENT 'ON by default for every seed row — values are placeholders pending legal confirmation',
    `notes`                 TEXT NULL DEFAULT NULL
        COMMENT 'Free-text notes; MAY include suggested public-anchor values labelled "confirm with legal" — never treated as authoritative by PHP',
    PRIMARY KEY (`regimeID`),
    UNIQUE KEY `uq_regime_code` (`regimeCode`),
    INDEX `idx_regime_active_draft` (`isActive`, `isDraft`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='One row per data-protection regime — the data-driven core of G-004 Layer 3';

-- ============================================================================
-- 🏗️ CREATE REGIME RIGHTS TABLE
-- ============================================================================
-- 🔗 Many-to-many: which DSAR rights a regime grants. `right` values MUST be
-- drawn from the SAME union DSARManager::VALID_REQUEST_TYPES mirrors from
-- tblDataSubjectRequests.requestType (migration 040): access|portability|
-- erasure|rectification|restriction|object|do_not_sell|withdraw_consent|
-- automated_decision_optout. No CHECK constraint is added (MySQL/MariaDB
-- portability + this migration's own "additive, no procs" house rule) —
-- RegimeResolver::rightsFor() and any future admin-CRUD validate against
-- that allowlist in PHP before writing a row.
-- ============================================================================

CREATE TABLE IF NOT EXISTS `tblRegimeRights` (
    `regimeID` SMALLINT UNSIGNED NOT NULL,
    `right`    VARCHAR(40) NOT NULL
        COMMENT 'One of DSARManager::VALID_REQUEST_TYPES — access|portability|erasure|rectification|restriction|object|do_not_sell|withdraw_consent|automated_decision_optout',
    PRIMARY KEY (`regimeID`, `right`),
    CONSTRAINT `fk_rr_regime` FOREIGN KEY (`regimeID`)
        REFERENCES `tblComplianceRegimes` (`regimeID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Which DSAR rights a regime grants (G-004 Layer 3)';

-- ============================================================================
-- 🏗️ CREATE REGIME DISCLOSURES TABLE
-- ============================================================================
-- 📜 Required disclosure sections per regime — drives future privacy-page
-- rendering. `title`/`body` are USER/LEGAL-SUPPLIED content and this
-- migration inserts ZERO rows into this table (nothing to seed — every
-- regime is a draft with no confirmed disclosure text yet).
-- ============================================================================

CREATE TABLE IF NOT EXISTS `tblRegimeDisclosures` (
    `disclosureID`  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `regimeID`      SMALLINT UNSIGNED NOT NULL,
    `disclosureKey` VARCHAR(64) NOT NULL
        COMMENT 'Stable key identifying which disclosure section this is, e.g. "categories_collected", "third_party_sharing"',
    `title`         VARCHAR(255) NULL DEFAULT NULL
        COMMENT 'USER/LEGAL-SUPPLIED section heading — ships NULL',
    `body`          TEXT NULL DEFAULT NULL
        COMMENT 'USER/LEGAL-SUPPLIED disclosure text — ships NULL/empty; NEVER generated by migration or PHP',
    PRIMARY KEY (`disclosureID`),
    INDEX `idx_regime_disclosure_regime` (`regimeID`, `disclosureKey`),
    CONSTRAINT `fk_rd_regime` FOREIGN KEY (`regimeID`)
        REFERENCES `tblComplianceRegimes` (`regimeID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Required disclosure sections per regime — content is user/legal-supplied (G-004 Layer 3)';

-- ============================================================================
-- 🏗️ CREATE REGIME RESOLUTION TABLE
-- ============================================================================
-- 🗺️ The rule table RegimeResolver::resolve() walks, ORDER BY priority ASC,
-- to decide which regime governs a given (userID, partnerID, countryHint).
--
-- ⚠️ DEVIATION FROM THE EARLIER SPEC DRAFT: `regimeID` here is NULLABLE and
-- carries NO foreign key (the spec draft sketched `NOT NULL` + an FK). This
-- is deliberate:
--   1. The seeded 'default' rule below MUST be able to express "there is no
--      specific regime for this catch-all — fall through to RegimeResolver's
--      synthetic most-protective PHP default" — that requires regimeID to be
--      NULL-able for at least that one row.
--   2. Omitting the FK means an admin (future cycle) can delete/deactivate a
--      regime without first hunting down every resolution rule that
--      references it — RegimeResolver::resolve() already treats "rule
--      matched but its target regime is not ACTIVE+non-draft" as "keep
--      walking lower-priority rules", so a dangling regimeID degrades safely
--      rather than needing referential-integrity enforcement at the DB layer.
--   3. Since every regime ships isActive=0 in this migration, resolution
--      falls through to the PHP default regardless of this table's
--      contents today — the seeded row below exists to document that the
--      default rule exists, not to change current behaviour.
-- ============================================================================

CREATE TABLE IF NOT EXISTS `tblRegimeResolution` (
    `ruleID`     INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `matchType`  ENUM('country','region','partner','default') NOT NULL
        COMMENT 'What kind of hint this rule matches against',
    `matchValue` VARCHAR(64) NULL DEFAULT NULL
        COMMENT 'ISO country code, region label, or partnerID (as a string) — NULL for matchType=default',
    `regimeID`   SMALLINT UNSIGNED NULL DEFAULT NULL
        COMMENT 'Target regime — NULLABLE, NO foreign key (see table comment above); NULL means "no specific regime, fall through to the PHP default"',
    `priority`   SMALLINT NOT NULL DEFAULT 100
        COMMENT 'Lower = evaluated first by RegimeResolver::resolve()',
    PRIMARY KEY (`ruleID`),
    INDEX `idx_resolution` (`matchType`, `matchValue`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Resolution rules RegimeResolver walks to pick a governing regime (G-004 Layer 3)';

-- 🌱 Seed ONE catch-all default rule (lowest priority = evaluated last).
-- Idempotent guard: only insert if no matchType='default' rule exists yet,
-- since this table has no natural UNIQUE key to ON-DUPLICATE-KEY against
-- (an admin may legitimately want several 'default'-adjacent rows later,
-- but this migration's job is only to document that the default rule
-- exists at all — never clobber an admin's later edits).
INSERT INTO `tblRegimeResolution` (`matchType`, `matchValue`, `regimeID`, `priority`)
SELECT 'default', NULL, NULL, 9999
WHERE NOT EXISTS (
    SELECT 1 FROM `tblRegimeResolution` WHERE `matchType` = 'default'
);

-- ============================================================================
-- 🌱 SEED THE 19 REGIMES NAMED IN THE PROJECT BRIEF (.claude/CLAUDE.md)
-- ============================================================================
-- Every row: isActive=0, isDraft=1, ALL value columns NULL. `notes` always
-- starts with the mandatory legal-confirmation warning; suggested PUBLIC
-- anchor numbers (clearly labelled) may follow, per the migration header.
-- Idempotent via ON DUPLICATE KEY UPDATE against UNIQUE(regimeCode) — never
-- clobbers an admin's later edits to any column.
-- ============================================================================

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('GDPR', 'General Data Protection Regulation', 'EU/EEA', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 30 days (extendable +60 for complex requests), breach notification to the supervisory authority within 72 hours, minimum digital-consent age 16 (Art. 8 GDPR — member states may lower to 13).')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('UK_GDPR', 'UK General Data Protection Regulation', 'United Kingdom', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 30 days (extendable +60), breach notification to the ICO within 72 hours, minimum digital-consent age 13 (UK GDPR / DPA 2018).')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('CCPA', 'California Consumer Privacy Act', 'California', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days (extendable +45), commonly understood to honor Global Privacy Control as a valid opt-out, requires a conspicuous "Do Not Sell My Personal Information" link.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('CPRA', 'California Privacy Rights Act', 'California', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days (extendable +45), commonly understood to honor Global Privacy Control, requires a "Do Not Sell or Share My Personal Information" link plus a "Limit the Use of My Sensitive Personal Information" right.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('VCDPA', 'Virginia Consumer Data Protection Act', 'Virginia', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days (extendable +45), commonly understood to honor opt-out preference signals (e.g. GPC) as of the 2023 amendment.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('CPA', 'Colorado Privacy Act', 'Colorado', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days (extendable +45), commonly understood to require honoring Universal Opt-Out Mechanisms (incl. GPC) from July 2024.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('CTDPA', 'Connecticut Data Privacy Act', 'Connecticut', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days (extendable +45), commonly understood to honor opt-out preference signals (e.g. GPC) from January 2025.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('UCPA', 'Utah Consumer Privacy Act', 'Utah', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 45 days; Utah does not currently mandate universal opt-out signal (e.g. GPC) recognition.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('HIPAA', 'Health Insurance Portability and Accountability Act', 'United States — health', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): access-request SLA 30 days (extendable +30), breach notification to affected individuals without unreasonable delay and no later than 60 days. Scope note: this is a HEALTH-DATA regime, distinct from the general consumer-privacy regimes above.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('COPPA', 'Children''s Online Privacy Protection Act', 'United States — children', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): minimum age 13 for processing a child''s personal information without verifiable parental consent; below this age routes to the parental-consent scaffold (G-004 Layer 4, not yet built).')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('LGPD', 'Lei Geral de Proteção de Dados', 'Brazil', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 15 days for data-subject request responses, breach notification to the ANPD within a "reasonable period".')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('PIPEDA', 'Personal Information Protection and Electronic Documents Act', 'Canada', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): SLA 30 days for access requests, breach notification "as soon as feasible" after determining a real risk of significant harm.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('APPI', 'Act on the Protection of Personal Information', 'Japan', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): no fixed statutory response-day count — "without delay" standard; breach notification to the PPC required for reportable incidents.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('PIPA', 'Personal Information Protection Act', 'South Korea', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): breach notification within 72 hours (5 days in some cases) to the PIPC and affected individuals.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('POPIA', 'Protection of Personal Information Act', 'South Africa', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): breach notification to the Information Regulator and data subjects "as soon as reasonably possible".')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('DPDP', 'Digital Personal Data Protection Act', 'India', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): breach notification to the Data Protection Board "without delay" (72 hours per draft rules); minimum age 18, with guardian consent required below that.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('PIPL', 'Personal Information Protection Law', 'China', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): breach notification "immediately"; minimum age 14 for a guardian''s consent to process a minor''s personal information.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('AU_PA88', 'Privacy Act 1988', 'Australia', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): Notifiable Data Breaches scheme requires notification to the OAIC and affected individuals "as soon as practicable"; access-request response commonly treated as 30 days.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

INSERT INTO `tblComplianceRegimes`
    (`regimeCode`, `displayName`, `jurisdiction`, `dsarSlaDays`, `dsarExtensionDays`,
     `breachNotifyHours`, `breachNotifyAuthority`, `minAge`, `honorsGPC`, `requiresDoNotSell`,
     `lawfulBasisRequired`, `isActive`, `isDraft`, `notes`)
VALUES
    ('NZ_PA20', 'Privacy Act 2020', 'New Zealand', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 1,
     '⚠️ Values pending legal confirmation — confirm all SLA/age/breach values with counsel before activating. Suggested (confirm with legal): breach notification to the Privacy Commissioner "as soon as practicable"; access-request response within 20 working days.')
    ON DUPLICATE KEY UPDATE regimeCode = regimeCode;

-- NB: tblRegimeRights / tblRegimeDisclosures are seeded with ZERO rows —
-- every regime above is a draft with no confirmed rights mapping or
-- disclosure text yet. That is deliberate (see migration header); the
-- future admin-CRUD workflow (G-004 spec §4.3) is where an operator both
-- activates a regime AND populates its rights/disclosures.

-- ============================================================================
-- ⚙️ SETTINGS (G-004 Layer 3)
-- ============================================================================
-- ONE new setting: the generic, country-agnostic most-protective-default
-- minimum age RegimeResolver::minAgeFor() falls back to when no active
-- regime resolves (or a resolved regime's minAge is itself NULL). This is
-- NOT a regime value — it names no jurisdiction — so it is safe to keep
-- configurable in tblSettings rather than a PHP literal. Real tblSettings
-- columns (verified against migration 040/041): settingKey, settingValue,
-- settingType, settingCategory, isSensitive, description.
-- ============================================================================

INSERT INTO `tblSettings` (`settingKey`, `settingValue`, `settingType`, `settingCategory`, `isSensitive`, `description`)
VALUES
    ('compliance.regime.default_min_age', '16', 'integer', 'privacy', 0,
     'Most-protective fallback minimum age used by RegimeResolver::minAgeFor() when no active regime resolves, or a resolved regime has not set its own minAge yet. Names no jurisdiction — a generic, operator-configurable ceiling.')
    ON DUPLICATE KEY UPDATE settingKey = settingKey;

-- ============================================================================
-- ✅ MIGRATION COMPLETE
-- ============================================================================
