-- ============================================================================
-- SIGNula Database Migration 044
--
-- Copyright (c) 2025-2026 MWBM Partners Ltd (t/a MWservices). All rights reserved.
--
-- 📋 Migration: Breach Notification + RoPA Register + COPPA Age-Gate (G-004 Layer 4b)
-- 📅 Date:      2026-07-10
-- 🔖 Version:   2.7.0-beta
-- 📝 Description:
--   The FINAL slice of G-004 (Layers 1-3 + L4a already BUILT). Creates:
--
--     - tblBreachIncidents      : one row per breach/incident an operator opens.
--     - tblBreachNotifications  : per-(incident,regime,audience) notification
--                                 obligation + computed deadline. BreachManager
--                                 (web/private_html/compliance/BreachManager.php)
--                                 is the ONLY PHP that writes these two tables.
--                                 It COMPUTES deadlines from
--                                 RegimeResolver::breachWindowHours() and
--                                 TRACKS status ONLY — it never auto-files with
--                                 a regulator and writes NO notification copy.
--                                 All summary/remediation/note text is operator
--                                 input; NOTHING is seeded/fabricated.
--
--     - tblProcessingActivities : Records of Processing Activities (RoPA)
--                                 register. Pure structure + CRUD — NO seeded
--                                 rows, NO fabricated purpose/lawfulBasis/
--                                 recipients text. An operator/DPO populates
--                                 every row via the admin UI.
--
--     - tblParentalConsents     : COPPA-style parental-consent scaffold.
--                                 `verificationToken` stores ONLY a SHA-256
--                                 HASH of the raw emailed token — mirrors the
--                                 tblDataSubjectRequests.verificationToken /
--                                 tblDataExportRequests.downloadToken lesson
--                                 (C5) exactly. The raw token is never
--                                 persisted or logged.
--
--   Plus 2 tblSettings rows that gate the age-gate feature:
--     - compliance.age_gate.enabled            : '0' (boolean) — OFF by
--       default. This is what keeps the register.php / Auth test baseline
--       green: with the gate off, register.php's age-gate block is skipped
--       entirely and behaves EXACTLY as it did before this migration.
--     - compliance.parental_consent.token_ttl_hours : '72' (integer) — TTL
--       for a parental-consent verification link once the gate is enabled.
--
-- 🔗 Related: .dev-team/specs/G-004.md §5.1, §5.2, §5.4 (Layer 4b — the FINAL
--    slice, completes G-004),
--    web/private_html/compliance/BreachManager.php,
--    web/private_html/compliance/AgeGateService.php,
--    web/private_html/compliance/RegimeResolver.php (breachWindowHours()/
--    minAgeFor() — the ONLY source of any regime-specific number; this
--    migration and every class it introduces name ZERO regime literals),
--    web/public_html/admin/compliance/breaches/index.php,
--    web/public_html/admin/compliance/ropa/index.php,
--    web/public_html/legal/parental-verify/index.php,
--    web/public_html/register.php (the age-gate signup hook),
--    _database/migrations/042_compliance_regimes.sql (RegimeResolver's data
--    source), _database/migrations/040_consent_and_dsar.sql (the
--    verificationToken SHA-256-hash pattern this migration mirrors).
-- ============================================================================

-- ============================================================================
-- 🚨 CREATE BREACH INCIDENT TABLES
-- ============================================================================

-- 🚨 One row per breach/incident an operator opens. NO seeds — an operator
-- opens these as real incidents occur; there is nothing safe to pre-populate.
CREATE TABLE IF NOT EXISTS `tblBreachIncidents` (
    `incidentID`         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `reference`           VARCHAR(32) NOT NULL
        COMMENT 'Human-readable reference, auto-generated by BreachManager::open() if not supplied, e.g. BRCH-2026-0001',
    `severity`            ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
    `status`              ENUM('detected','assessing','contained','notifying','closed') NOT NULL DEFAULT 'detected',
    `detectedAt`          DATETIME NOT NULL
        COMMENT 'When the incident was detected — the anchor computeNotificationDeadlines() adds each regime breachNotifyHours() window to',
    `discoveredBy`        VARCHAR(255) NULL DEFAULT NULL,
    `affectedUserCount`   INT UNSIGNED NULL DEFAULT NULL,
    `dataCategories`      JSON NULL DEFAULT NULL
        COMMENT 'Which PII categories were exposed — operator-entered',
    `regimeCodes`         JSON NULL DEFAULT NULL
        COMMENT 'JSON array of tblComplianceRegimes.regimeCode values this incident triggers — drives computeNotificationDeadlines()',
    `summary`             TEXT NULL DEFAULT NULL COMMENT 'Operator/DPO-authored incident summary — never auto-generated',
    `remediation`         TEXT NULL DEFAULT NULL COMMENT 'Operator/DPO-authored remediation notes — never auto-generated',
    `assignedAdminID`     BIGINT UNSIGNED NULL DEFAULT NULL,
    `createdAt`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`incidentID`),
    UNIQUE KEY `uq_breach_reference` (`reference`),
    INDEX `idx_breach_status` (`status`),
    INDEX `idx_breach_detected` (`detectedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Breach-notification incident log (G-004 Layer 4b §5.1) — machinery only, no fabricated content';

-- 📨 Per (incident, regime, audience) notification obligation + computed
-- deadline. One row per audience per triggered regime (an incident naming
-- 3 regimeCodes produces up to 6 rows: authority+data_subjects x 3 regimes).
CREATE TABLE IF NOT EXISTS `tblBreachNotifications` (
    `notifyID`    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `incidentID`  BIGINT UNSIGNED NOT NULL,
    `regimeCode`  VARCHAR(16) NULL DEFAULT NULL
        COMMENT 'Soft link to tblComplianceRegimes.regimeCode — no FK (regime config may change independently)',
    `audience`    ENUM('authority','data_subjects') NOT NULL,
    `dueAt`       DATETIME NULL DEFAULT NULL
        COMMENT 'detectedAt + RegimeResolver::breachWindowHours(regimeCode) hours — NULL when the regime has no configured window (graceful degrade, never a crash)',
    `status`      ENUM('pending','sent','not_required') NOT NULL DEFAULT 'pending',
    `sentAt`      DATETIME NULL DEFAULT NULL,
    `note`        TEXT NULL DEFAULT NULL
        COMMENT 'Operator-entered note — e.g. "no breachNotifyHours configured for this regime yet" when dueAt is NULL, or the operator''s own filing notes',
    PRIMARY KEY (`notifyID`),
    CONSTRAINT `fk_breachnotify_incident` FOREIGN KEY (`incidentID`)
        REFERENCES `tblBreachIncidents` (`incidentID`) ON DELETE CASCADE,
    UNIQUE KEY `uq_breach_notify_target` (`incidentID`, `regimeCode`, `audience`),
    INDEX `idx_breach_notify_due` (`status`, `dueAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Per-regime/audience breach notification deadlines + status (G-004 Layer 4b §5.1)';

-- ============================================================================
-- 📋 CREATE ROPA (RECORDS OF PROCESSING ACTIVITIES) REGISTER
-- ============================================================================

-- 📋 RoPA register. Pure structure + CRUD — NO seeded rows with real content.
-- Every purpose/lawfulBasis/recipients/retentionPeriod value is operator/DPO
-- input; the tool never fabricates legal-basis determinations.
CREATE TABLE IF NOT EXISTS `tblProcessingActivities` (
    `activityID`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `activityKey`             VARCHAR(64) NOT NULL COMMENT 'Stable short key, operator-chosen, e.g. user_account_management',
    `name`                    VARCHAR(255) NOT NULL,
    `purpose`                 TEXT NULL DEFAULT NULL COMMENT 'Operator/DPO-authored — never fabricated',
    `lawfulBasis`             VARCHAR(128) NULL DEFAULT NULL COMMENT 'Operator/DPO-authored legal-basis determination — never fabricated',
    `dataCategories`          JSON NULL DEFAULT NULL,
    `dataSubjectCategories`   JSON NULL DEFAULT NULL,
    `recipients`              JSON NULL DEFAULT NULL COMMENT 'Third-party processor list — operator-authored',
    `retentionPeriod`         VARCHAR(128) NULL DEFAULT NULL,
    `transfersOutsideRegion`  JSON NULL DEFAULT NULL,
    `regimeCodes`             JSON NULL DEFAULT NULL COMMENT 'JSON array of tblComplianceRegimes.regimeCode values this activity is governed by',
    `ownerAdminID`            BIGINT UNSIGNED NULL DEFAULT NULL,
    `isActive`                TINYINT(1) NOT NULL DEFAULT 1,
    `createdAt`               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt`               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`activityID`),
    UNIQUE KEY `uq_ropa_activity_key` (`activityKey`),
    INDEX `idx_ropa_active` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Records of Processing Activities register (G-004 Layer 4b §5.2) — structure + CRUD only, zero fabricated content';

-- ============================================================================
-- 👶 CREATE PARENTAL CONSENT SCAFFOLD (COPPA age-gate)
-- ============================================================================

-- 👶 Parental-consent tracking. `verificationToken` stores ONLY a SHA-256
-- HASH — mirrors tblDataSubjectRequests.verificationToken (migration 040)
-- exactly; the raw token is emailed once and never persisted.
CREATE TABLE IF NOT EXISTS `tblParentalConsents` (
    `consentID`          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `childUserID`         BIGINT UNSIGNED NOT NULL,
    `parentEmail`         VARCHAR(255) NOT NULL,
    `status`              ENUM('pending','verified','denied') NOT NULL DEFAULT 'pending',
    `verificationToken`   CHAR(64) NULL DEFAULT NULL
        COMMENT 'SHA-256 HEX HASH of the raw emailed verification token — NEVER the raw token itself (mirrors migration 040''s tblDataSubjectRequests.verificationToken pattern)',
    `method`              VARCHAR(64) NULL DEFAULT NULL
        COMMENT 'Verification method used — the METHOD SUFFICIENCY under COPPA is a legal call; this column just records which method was used (e.g. email_link)',
    `verifiedAt`          DATETIME NULL DEFAULT NULL,
    `createdAt`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`consentID`),
    INDEX `idx_parental_child` (`childUserID`),
    INDEX `idx_parental_status` (`status`)
    -- ⚠️ No hard FK to tblUsers deliberately: mirrors tblDataSubjectRequests'
    -- own "no hard FK to tblUsers" contract (migration 040) — a parental
    -- consent audit row should be able to outlive the child account row
    -- through any future erasure workflow without an ON DELETE CASCADE
    -- silently destroying the consent evidence.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='COPPA-style parental-consent scaffold (G-004 Layer 4b §5.4) — verificationToken is ALWAYS a SHA-256 hash, never raw';

-- ============================================================================
-- ⚙️ SETTINGS (G-004 Layer 4b)
-- ============================================================================
-- Real tblSettings columns (verified against migrations 040/041/042/043):
--   settingKey, settingValue, settingType, settingCategory, isSensitive, description
-- ============================================================================

-- 🚫 Age-gate master switch — OFF by default. THIS is what keeps the
-- register.php / Auth test baseline green: with the gate off,
-- AgeGateService::isEnabled() returns false and register.php's entire
-- age-gate block (DOB read + underage check + parental-consent routing) is
-- skipped, so register.php behaves EXACTLY as it did before this migration.
INSERT INTO `tblSettings` (`settingKey`, `settingValue`, `settingType`, `settingCategory`, `isSensitive`, `description`)
VALUES
    ('compliance.age_gate.enabled', '0', 'boolean', 'privacy', 0,
     'Master switch for the COPPA-style signup age-gate. OFF (0/false) by default — while OFF, register.php never reads/requires a date_of_birth field and AgeGateService::isEnabled() returns false everywhere. An operator must explicitly enable this (after confirming the applicable minimum-age threshold with legal via the Compliance Regimes admin) before any signup is age-gated.')
    ON DUPLICATE KEY UPDATE `settingKey` = `settingKey`;

-- ⏰ Parental-consent verification link TTL (hours).
INSERT INTO `tblSettings` (`settingKey`, `settingValue`, `settingType`, `settingCategory`, `isSensitive`, `description`)
VALUES
    ('compliance.parental_consent.token_ttl_hours', '72', 'integer', 'privacy', 0,
     'Lifetime (in hours) of a parental-consent email verification link, from AgeGateService::startParentalConsent() issuance. Only consulted when compliance.age_gate.enabled is true.')
    ON DUPLICATE KEY UPDATE `settingKey` = `settingKey`;

-- ============================================================================
-- ✅ MIGRATION COMPLETE — G-004 FULLY BUILT (Layers 1-3 + L4a + L4b)
-- ============================================================================
