<?php
/**
 * ============================================================================
 * ✅ SIGNula - Data Request Identity Verification Landing (G-004 Layer 1 / Cycle C)
 * ============================================================================
 *
 * Purpose: The landing page for the emailed verification link
 *          (/legal/data-request/verify?requestID=N&token=...) generated by
 *          DataRequestIntake::process() (public form) or the admin queue's
 *          "Send / Re-send Identity Verification Email" action. Calls
 *          DSARManager::verifyIdentity() and shows a generic success/failure
 *          message — never anything more specific (DSARManager::verifyIdentity()
 *          itself fails closed and uniformly for every rejection reason —
 *          not-found, wrong status, bad token, expired — by design, so this
 *          page has nothing more specific to reveal even if it wanted to).
 *
 * PHP Version: 8.3+
 *
 * @see web/private_html/compliance/DSARManager.php — verifyIdentity()
 * @see web/public_html/SIGNula.com/legal/data-request/index.php — where the link is emailed from
 * @see .dev-team/specs/G-004.md §2.6
 *
 * Copyright (c) 2025-2026 MWBM Partners Ltd (t/a MWservices). All rights reserved.
 *
 * @package    SIGNula
 * @subpackage Marketing\Legal\DataRequest
 * @version    1.0.0
 * @since      2.7.0-beta
 * ============================================================================
 */

// ⚠️ PATH DEPTH: this file sits directly alongside index.php inside
// SIGNula.com/legal/data-request/ — SAME depth, SAME dirname(__DIR__, 4).
require_once dirname(__DIR__, 4) . DIRECTORY_SEPARATOR . '_config' . DIRECTORY_SEPARATOR . 'config.php';

if (!class_exists('DSARManager')) {
    require_once dirname(__DIR__, 4) . DIRECTORY_SEPARATOR . 'private_html'
        . DIRECTORY_SEPARATOR . 'compliance' . DIRECTORY_SEPARATOR . 'DSARManager.php';
}

$pageTitle = 'Verify Your Data Request - SIGNula';
$metaDescription = 'Verify your identity to continue your SIGNula data request.';
$currentPage = 'data-request';

$requestID = (int) ($_GET['requestID'] ?? 0);
$token = (string) ($_GET['token'] ?? '');

$verified = false;

if ($requestID > 0 && $token !== '') {
    try {
        // 🔒 verifyIdentity() fails CLOSED (returns false, never throws) for
        // every rejection reason — this page never learns, and therefore
        // never can leak, WHY a verification failed.
        $verified = DSARManager::verifyIdentity($requestID, $token);
    } catch (\Throwable $e) {
        $verified = false;
    }
}

require_once dirname(__DIR__, 4) . DIRECTORY_SEPARATOR . 'private_html' . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'public-header.php';
?>

<section class="section-padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7 text-center">
                <?php if ($verified): ?>
                <i class="fas fa-circle-check fa-4x text-success mb-4"></i>
                <h1 class="h3 mb-3">Identity Verified</h1>
                <p class="text-secondary">
                    Thank you — we've confirmed your identity for this data request. Our team will review and
                    follow up with you by email.
                </p>
                <?php else: ?>
                <i class="fas fa-circle-xmark fa-4x text-danger mb-4"></i>
                <h1 class="h3 mb-3">Verification Link Invalid Or Expired</h1>
                <p class="text-secondary">
                    This link may have already been used, or may have expired. If you still need to make a
                    request, please submit a new one below.
                </p>
                <a href="/legal/data-request" class="btn btn-primary mt-2">
                    <i class="fas fa-paper-plane me-2"></i>Submit A New Request
                </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>

<?php
require_once dirname(__DIR__, 4) . DIRECTORY_SEPARATOR . 'private_html' . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'public-footer.php';
?>
